# -*- coding: utf-8 -*-
"""Latihan CNN dengan DNN

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DeOT9cRh7TwVagGT7ifOB1Lmza9NjhL9
"""

from tensorflow.keras import datasets
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten, Dropout,Dense
from tensorflow.keras.layers import AveragePooling2D, Conv2D

"""Unduh dataset MNIST"""

mnist = datasets.mnist
(X_train, y_train), (X_test, y_test) = mnist.load_data()

"""GPU"""

!nvidia-smi

"""Normalisasi nilai pixel"""

X_train = X_train/255.0
X_test = X_test/255.0

"""# **Model DNN dengan 2 hidden layers dan Regulation Dropout**"""

model4 = Sequential()
model4.add(Flatten(input_shape=[28, 28]))
model4.add(Dropout(0.3))
model4.add(Dense(128, activation='relu'))
model4.add(Dropout(0.3))
model4.add(Dense(128, activation='relu'))
model4.add(Dropout(0.3))
model4.add(Dense(10, activation='softmax'))

"""Optimasi ADAM"""

model4.compile(loss='sparse_categorical_crossentropy',
optimizer='Adam', metrics=['accuracy'])

"""Eksperimen sampai 50 epochs"""

model4.fit(X_train, y_train, epochs=50,
validation_split=0.2,
batch_size=128)

"""Evaluasi Model"""

model4.evaluate(X_test, y_test)